/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.text.Format;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Chathura
 */
public class MainWindow extends javax.swing.JFrame {

    public static MainWindow mainWindow;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        mainWindow = this;
        // this.setUndecorated(true);

        this.setExtendedState(MAXIMIZED_BOTH);
        createUI();

        AddSuplier as = new AddSuplier(false);
        openWindow(as);
        
        Icon i=new Icon("Supplier", new ImageIcon(getClass().getResource("/ui/images/icons/supplier.png")));
        iconPanel.add(i);
        
        Icon i2=new Icon("Customer", new ImageIcon(getClass().getResource("/ui/images/icons/customer.png")));
        iconPanel.add(i2);


    }

    private void createUI() {

        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();

        JLayeredPane desktop = this.desktop;
        desktop.setBounds(0, 60, screen.width, screen.height - 60);

        backgroundTxt.setIcon(new ImageIcon(getClass().getResource("/ui/images/background.jpg")));
        backgroundTxt.setBounds(0, 0, screen.width, screen.height);

        topBar.setSize(screen.width, 60);
        topBar.setLocation(0, 0);

        //time
        TimerTask timeUpdate = new TimerTask() {

            @Override
            public void run() {
                Date d = new Date();
                dateTxt.setText(d.getHours() + " : " + d.getMinutes() + " : " + d.getSeconds());
            }
        };

        Timer t = new Timer();
        t.scheduleAtFixedRate(timeUpdate, 0, 1000);

        dateTxt.setBounds(0, screen.height - 150, screen.width - 30, 120);
        
        iconPanel.setBounds(50, 100, screen.width, screen.height);
        iconPanel.setOpaque(false);

    }

    public static MainWindow getInstance() {
        return mainWindow;
    }

    public void openWindow(JInternalFrame frame) {
        JLayeredPane desktop = this.desktop;

        desktop.add(frame);

        frame.setLocation((this.desktop.getWidth() - frame.getWidth()) / 2, (this.desktop.getHeight() - frame.getHeight()) / 2);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topBar = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g) {
                Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();

                g.setColor(new Color(0f,0f,0f,0.5f));
                g.fillRect(0, 0, screen.width, 60);
            }
        };
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        desktop = new javax.swing.JLayeredPane();
        iconPanel = new javax.swing.JPanel();
        dateTxt = new javax.swing.JLabel();
        backgroundTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Invictuz Hotels");

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(topBar);
        topBar.setBounds(0, 0, 639, 66);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        getContentPane().add(desktop);
        desktop.setBounds(397, 184, 242, 116);

        iconPanel.setBackground(new java.awt.Color(0, 255, 153));
        iconPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15));
        getContentPane().add(iconPanel);
        iconPanel.setBounds(470, 90, 160, 170);

        dateTxt.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        dateTxt.setForeground(new java.awt.Color(255, 255, 255));
        dateTxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateTxt.setText("date");
        getContentPane().add(dateTxt);
        dateTxt.setBounds(200, 110, 140, 90);
        dateTxt.getAccessibleContext().setAccessibleName("date");

        backgroundTxt.setText("jLabel1");
        getContentPane().add(backgroundTxt);
        backgroundTxt.setBounds(80, 120, 76, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*SwingUtilities.invokeLater(new Runnable() {
         @Override
         public void run() {
         // Install WebLaF as application L&F
         WebLookAndFeel.install();
         }
         });*/
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }//*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundTxt;
    private javax.swing.JLabel dateTxt;
    private javax.swing.JLayeredPane desktop;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel topBar;
    // End of variables declaration//GEN-END:variables
}
